name = "Developers Dungeon SMP"
version = "v0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8369a9b4d268fe43f2eeba40f798f3a99d04a3251c7ebe6b699370b4476fe31"

[versions]
fabric = "0.16.2"
minecraft = "1.21.1"
