name = "Developers Dungeon SMP"
version = "v0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56b50eef4f564044efc7db708cebc03b886d0df4e4b3ef15cb8d2a893371ed03"

[versions]
fabric = "0.16.2"
minecraft = "1.21.1"
