name = "Developers Dungeon SMP"
version = "v0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5625c6229c1c3974082dc79f526434d94c7548213bd7f702ac65c81b403a9f0"

[versions]
fabric = "0.16.2"
minecraft = "1.21.1"
