name = "Developers Dungeon SMP"
version = "v0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95fc6abf4dd71eb9f17b94e383d35292b040c981c0e4a1cf776a4b10e7cb571e"

[versions]
fabric = "0.16.2"
minecraft = "1.21.1"
